server:
  port: 8080

spring:
  application:
    name: learning-web

dubbo:
  application:
    name: learning-web
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    check: false
    timeout: 5000

logging:
  level:
    com.example.learning: info
